apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
spec:
  selector:
    matchLabels:
      app: spring-boot-app
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
      - name: spring-boot-app
        image: nadiaabdelmoula/gestioncompetenceback
        ports:
        - containerPort: 5000
        env:
        - name: SPRING_DATASOURCE_URL
          value:  jdbc:mysql://mysqldbGestcomp:3306/pfeDataBase?createDatabaseIfNotExist=true&useSSL=false
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: password
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app
spec:
  selector:
    app: spring-boot-app
  ports:
  - name: http
    port: 80
    targetPort: 5000
