apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-k8s-mysql
  namespace: appdep
spec:
  selector:
    matchLabels:
      app: springboot-k8s-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: springboot-k8s-mysql
    spec:
      containers:
        - name: gestioncompetenceback
          image: nadiaabdelmoula/gestioncompetenceback
          ports:
            - containerPort: 5000
          env:   # Setting Enviornmental Variables
            - name: DB_HOST   # Setting Database host address from configMap
              value: mysqldbgestcomp
            - name: DB_NAME  # Setting Database name from configMap
              value: pfeDataBase
            - name: DB_USERNAME  # Setting Database username from Secret
              value: root
            - name: DB_PASSWORD # Setting Database password from Secre
              value: root
            - name: MYSQL_PORT
              value: "3306"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysqldbgestcomp:3306/pfeDataBase?createDatabaseIfNotExist=true&useSSL=false&useJDBCCompliantTimezoneShift=true&serverTimezone=UTC

---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: springboot-k8s-mysql
  namespace: appdep
spec:
  selector:
    app: springboot-k8s-mysql
  ports:
    - protocol: "TCP"
      port: 5000 # The port that the service is running on in the cluster
      targetPort: 5000 # The port exposed by the service
  type: NodePort # type of the service.

