apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-deployment
  namespace: appdep
spec:
  selector:
    matchLabels:
      app: spring-boot
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-boot
    spec:
      containers:
      - name: gestioncompetenceback
        image: nadiaabdelmoula/gestioncompetenceback
        ports:
        - containerPort: 5000
        
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-deployment
  namespace: appdep
spec:
  selector:
    matchLabels:
      app: sql
  replicas: 1
  template:
    metadata:
      labels:
        app: sql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        ports:
        - containerPort: 3306 # Replace with your SQL server port number


