apiVersion: apps/v1
kind: Deployment
metadata:
  name: gestioncompetence-deployment
  labels:
    app: gestioncompetenceback
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gestioncompetenceback
  template:
    metadata:
      labels:
        app: gestioncompetenceback 
    spec:
      containers:
      - name: gestioncompetenceback
        image: nadiaabdelmoula/gestioncompetenceback
        ports:
        - containerPort: 3000
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: gestioncompetence-service
spec:
  selector:
    app: gestioncompetenceback 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 5000
