apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  namespace: appdep
  labels:
    app: backend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: backend-app
      app: backend-app
  template:
    metadata:
      name: backend-app
      labels:
        name: backend-app
        app: backend-app

    spec:
      containers:
      - name: backend-app
        image: nadiaabdelmoula/gestioncompetenceback
        env:
          - name: spring.datasource.url
            value: jdbc:mysql://mysqldbgestcomp:3306/pfeDataBase?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
          - name: spring.datasource.username
            value: root
          - name: spring.datasource.password
            value: root
        ports:
        - containerPort: 80
