version: "3"
services:
  gestcomp:
    build: .
    image: gestioncompetenceback
    container_name: gestcompcontainer
    #image: nadiaabdelmoula/gestioncompetenceback
    #container_name: gestioncompetenceback
    ports:
      - "5000:5000"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldbGestcomp:3306/pfeDataBase?createDatabaseIfNotExist=true&useSSL=false
    networks:
      - springmysql-net
    depends_on:
      - mysqldbGestcomp

  mysqldbGestcomp:
    image: mysql:5.7
    container_name: mysqlcontainer
    networks:
      - springmysql-net
    environment:
      - MYSQL_DATABASE=pfeDataBase
      - MYSQL_ROOT_PASSWORD=root
      #- MYSQL_ALLOW_EMPTY_PASSWORD="yes"

networks:
  springmysql-net: 
