apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: gestcompcontainer
      image: nadiaabdelmoula/gestioncompetenceback
      ports:
        - containerPort: 5000
      env:
        - name: MYSQL_URL
          value: jdbc:mysql://mysqldbgestcomp:3306/pfeDataBase?createDatabaseIfNotExist=true&useSSL=false&useJDBCCompliantTimezoneShift=true&serverTimezone=UTC
    - name: mysqlcontainer
      image: mysql:5.7
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          value: pfeDataBase
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASSWORD
          value: root
        - name: MYSQL_URL
          value: jdbc:mysql://mysqldbgestcomp:3306/pfeDataBase?createDatabaseIfNotExist=true&useSSL=false&useJDBCCompliantTimezoneShift=true&serverTimezone=UTC

