apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldbgestcomp
  namespace: appdep
  labels:
    app: mysqldbgestcomp
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysqldbgestcomp
      app: mysqldbgestcomp
  template:
    metadata:
      name: mysqldbgestcomp
      labels:
        name: mysqldbgestcomp
        app: mysqldbgestcomp

    spec:
      containers:
      - name: mysqldbgestcomp
        image: mysql:5.7
        ports:
        - containerPort: 3306
