apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
    tier: database
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql
    tier: database
  clusterIP: None # DNS is used, so clusterIP is not needed
      
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
    tier: database
spec:
  selector: # mySQL Pod Should contain same labels
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels: # Must match 'Service' and 'Deployment' selectors
        app: mysql
        tier: database
    spec:
      containers:
        - name: mysqlcontainer
          image: mysql:5.7
          imagePullPolicy: "IfNotPresent"
          env:
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "yes"
            - name: MYSQL_DATABASE
              value: pfeDataBase
          ports:
            - containerPort: 3306
              name: mysqlcontainer
          #volumeMounts:
           # - mountPath: /var/lib/mysql
            #  name: mysql-persistance-storage
      #volumes:
       # - name: mysql-persistance-storage
        #  persistentVolumeClaim:
         #   claimName: mysql-pv-claim
  
