apiVersion : v1
kind : ConfigMap
metadata:
  name : db-config
data:
  host : mysqldbgestcomp
  dbName: pfeDataBase
  mysqlport: "3306"
  url: jdbc:mysql://mysqldbgestcomp:3306/pfeDataBase?createDatabaseIfNotExist=true&useSSL=false
