apiVersion: v1
kind: Service
metadata:
  name: backend-app
  namespace: appdep
  labels:
    name: backend-app
    app: backend-app
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    name: backend-app
    app: backend-app
